# Use Node.js base image for development
FROM node:18 AS base

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy application code
COPY . .

# Expose the port for your application
EXPOSE 8000

# Set the default command for the container in development mode
CMD ["npm", "run", "dev"]
