name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy SSH private key to GitHub actions
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # SSH into VPS and navigate to project directory
            if [ ! -d "HRMS" ]; then
              git clone git@github.com:mukeshkr2024/HRMS.git
            else
              cd HRMS
              git pull origin master
            fi

            cd HRMS

            docker compose pull
            docker compose build --no-cache
            docker compose up -d --no-deps --build --remove-orphans backend frontend

      - name: Clean up SSH private key
        run: rm -f private_key
